# Azure Pipeleines # YAML
# in steps just write - task: Maven@4  => then settings option will appear click on it and update goal with install
# and add like this down all mater will come and adjust the spaces for lines
trigger: none

pool:
  vmImage: windows-latest

stages:
  - stage: dev
    jobs:
      - job: gitcode
        steps:
          - checkout: self
  - stage: 'Build'
    jobs:
      - job: 'BuildJob'
        steps:
        - task: Maven@4
          inputs:
           mavenPomFile: 'pom.xml'
           goals: 'install'
           publishJUnitResults: true
           testResultsFiles: '**/surefire-reports/TEST-*.xml'
           javaHomeOption: 'JDKVersion'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false
           effectivePomSkip: false
           sonarQubeRunAnalysis: false