trigger:
- master
pool:
  vmImage: ubuntu-latest
stages:
- stage: dev
  jobs:
    - job: devjob
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world'
- stage: qa
  jobs:
    - job: qajob
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'my name is sagar'
- stage: prod
  jobs:
    - job: prodjob
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'done prod'
            